#!/bin/bash

format() {
	for _SOURCE_FILE in $(find . -type f | grep \\.go$)
	do
		gofmt -s -w $_SOURCE_FILE
	done
}

_lint() {
	golangci-lint run --fix ./
}

_clean() {
	rm -f go.mod go.sum
}

_fetch_latest_package() {
	go get -u $_GITHUB_MODULE_PATH/$_LIBRARY
}
