substitutions:
  _APP: github.com/walterjwhite/go-code/cmd/example/rest/gin
  _BUCKET: go-rest-example-180831-bucket

steps:
- name: "gcr.io/cloud-builders/go"
  args:
  - get
  - "google.golang.org/appengine"
  env: 
  - "GOPATH=go"
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - app
  - deploy
  - "go/src/${_APP}"
  env:
  - "GOPATH=go"

artifacts:
  objects:
    location: 'gs://${_BUCKET}/'
    paths: "go/src/${_APP}/main.go"
