#!/bin/bash

source ./.helpers/libraries/format

_GITHUB_MODULE_PATH=github.com/walterjwhite/go-application/libraries
_PWD=$(pwd)

_build_library() {
	cd $_LIBRARY
	
	local _HAS_GO_FILES=$(find . -maxdepth 1 -type f  | grep \\.go$ | wc -l)
	if [ "$_HAS_GO_FILES" -gt "0" ]
	then
		echo -e "building library: $_LIBRARY"
	
		format
		_lint
		_setup_module
		go build
	fi
	
	cd $_PWD
}

_setup_module() {
	if [ ! -e go.mod ]
	then
		go mod init $_GITHUB_MODULE_PATH/$(basename $_LIBRARY)
	fi
}

_build_libraries() {
	for _LIBRARY in $@
	do
		_build_library
	done
}

_lint() {
	golangci-lint run --fix ./
}

if [ "$#" -eq "0" ]
then
	_build_libraries $(find libraries -type d | sort -u)
else
	_build_libraries $@
fi
