#!/bin/bash

source ./.helpers/libraries/format

_build_library() {
	_PWD=$(pwd)
	
	cd $_LIBRARY
	
	echo -e "building library: $_LIBRARY"
	
	format
	
	vgo build
	
	cd $_PWD
}

_build_libraries() {
	for _LIBRARY in $@
	do
		_build_library
	done
}



if [ "$#" -eq "0" ]
then
	_build_libraries $(find libraries -type f | grep gopkg.toml$ | sed -e "s/\/gopkg\.toml$//")
else
	_build_libraries $@
fi
