#!/bin/bash

source ./.helpers/libraries/format

_GITHUB_MODULE_PATH=github.com/walterjwhite/go-application/libraries

_build_library() {
	_PWD=$(pwd)
	
	cd $_LIBRARY
	
	echo -e "building library: $_LIBRARY"
	
	format
	_setup_module
	go build
	
	cd $_PWD
}

_setup_module() {
	if [ ! -e go.mod ]
	then
		go mod init $_GITHUB_MODULE_PATH/$(basename $_LIBRARY)
	fi
}

_build_libraries() {
	for _LIBRARY in $@
	do
		_build_library
	done
}



if [ "$#" -eq "0" ]
then
	_build_libraries $(find libraries -type f | grep gopkg.toml$ | sed -e "s/\/gopkg\.toml$//")
else
	_build_libraries $@
fi
