name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
# not yet supported, @see: https://github.com/marketplace/actions/freebsd-vm
#          - { runner: freebsd-latest,  os: freebsd,  arch: amd64, env: CGO_ENABLED=0 }
          - { runner: macos-latest,  os: darwin,  arch: amd64, tags: netcgo        }
          - { runner: ubuntu-latest, os: linux,   arch: amd64, env:  CGO_ENABLED=0 }
#          - { runner: windows-latest, os: windows, arch: amd64, env:  CGO_ENABLED=0 }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: build
        run: |
          go get -u
          go mod tidy
          cd lib
          go build -a -race
          cd ../cmd
          
          go install -a race
#       - name: upload
#         uses: actions/upload-artifact@v3
#         with:
#           name: 
        
#       - name: Build
#         uses: hashicorp/actions-go-build@main
#         with:
#           product_name: go-code
#           product_version: 0.0.0
#           go_version: 1.18
#           os: ${{ matrix.os }}
#           arch: ${{ matrix.arch }}
#           instructions: |-
#             ${{ matrix.env }} \
#               go build \
#                 -o "$BIN_PATH" \
#                 -trimpath \
#                 -buildvcs=false \
#                 -tags="${{ matrix.tags }}" \
#                 -ldflags "
#                   -X 'main.Version=$PRODUCT_VERSION'
#                   -X 'main.Revision=$PRODUCT_REVISION'
#                   -X 'main.RevisionTime=$PRODUCT_REVISION_TIME'
#                 "
